apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      serviceAccountName: builder
      containers:
        - name: controller
          image: controller:v1
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: neo4j-secret
